### ISSUE TITLE
Find a way to identify if automation-tools is running as a library

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/automation-tools#110]
If automation-tools is being run as a library then it should not call `sys.exit`.

One option is to check if Fabric will return a non-zero return code if a task returns a non-zero integer. This way won't be needed to call `sys.exit`.

**Comment by Ichimonji10** [comment]
```python
if __name__ == '__main__':
    pass
```

**Comment by Ichimonji10** [comment]
Or something similar.

```python
if automation_tools.__name__ == '__main__':
    print('automation_tools.__init__ is being called directly')
```

**Comment by rplevka** [comment]
How about using [ __module__ ](https://docs.python.org/2/reference/datamodel.html) attribute (Python >=2.6)?
```bash
$ cat foo.py
def bar():
    print '42'
print bar.__module__

$ python foo.py
__main__

$ python
Python 2.7.8 (default, Apr 15 2015, 09:26:43) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from foo import bar
foo
>>>
```
in case the return value is not `__main__`, the function is being ran as a library

**Comment by elyezer** [comment]
Closing this issue as it is not valid anymore. Automation tools is not intended to be used as a python library but a helper to configure machines using the fab command line utility.
