### ISSUE TITLE
Add tasks to help filing BZ bug

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/automation-tools#137]
Add tasks to collect packages versions and foreman-debug information.

**Comment by omaciel** [comment]
Cool. Let's then collect the list of packages installed and run foreman-debug (must be careful to avoid the non-interactive mode, which prompts you to upload the generated logs to a Foreman server), copying it to your local filesystem.

BONUS: in the feature we could have Robottelo file a BZ for failed tests and attach all this information :)

**Comment by Ichimonji10** [comment]
I wonder if foreman-debug has a switch that says "do not upload logs"?

**Comment by elyezer** [comment]
@Ichimonji10 `foreman-debug -q`does the trick, but it is better to also specify `-d`, because in the quiet mode it does not even print what the resulting tarball is.

Which the -d it creates a directory where specified and inside it creates a `<direcotory-name>.tar.xz ` which will make easier to grab it.

**Comment by elyezer** [comment]
@omaciel that list of package is not necessary anymore as foreman-debug already grabs that information. More information about it in QE list.

**Comment by sthirugn** [comment]
yes what @elyezer said, just foreman-debug is good which already has *all* the installed packages version.
