### ISSUE TITLE
setup_vm_provisioning checks for a nested virtualization support prior to virtualization support itself

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/automation-tools#169]
`setup_vm_provisioning` first checks for a nested virtualization support on the machine by checking the output of _/sys/module/kvm_intel/parameters/nested_ file.
If not supported, it tries to enable it and prompts user to reboot the host.
After that, it is supposed to proceed in code and start checking for virtualization support. This stage cannot be reached in case no virtualization support exists on the host thus I believe these checks should be swapped.

**Comment by elyezer** [comment]
Seems that file is not available if kvm is not installed which will make this task never proceed. Good catch.
