### ISSUE TITLE
Unsubscribe before destroying a virtual machine

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/automation-tools#173]
Make sure to run unsubscribe task before destroying a virtual machine in order to release any subscription consumed during the provisioning.

**Comment by omaciel** [comment]
Just run ``subscription-manager unregister``

**Comment by elyezer** [comment]
This will be solved by creating a job that will clean the subscriptions used by the automation virtual machines.

**Comment by elyezer** [comment]
The job is already in place and running every week cleaning subscriptions older than 7 days.
