### ISSUE TITLE
refactor product_install task for Sat5 

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/automation-tools#177]
We need further refactor to make the product_install task install Satellite 5
Currently we used iso_install task as a teplate for sat5_iso_install task, so it has to mimics what it returns to product_install task.

**Comment by elyezer** [comment]
The design decision behind product_install and all *_install tasks was that every install task should return a map for installer options, then the katello_installer task grab that information and run the install command. One way to refactor is to adopt the same approach for Satellite 5 related tasks or think a different approach and make product_install handle it if doing a Satellite 5 installation.

**Comment by Ichimonji10** [comment]
Thanks for the explanation, @elyezer.

**Comment by lpramuk** [comment]
I'd go for separate satellite5_product_install to avoid frequent if conditions for sat5 vs. sat6

**Comment by elyezer** [comment]
:+1:

**Comment by lpramuk** [comment]
Submitted PR #180 
Oops, looks like I missed elyezer last comment, yet I'd like to incorporate it in.

**Comment by lpramuk** [comment]
Resolved as PR #180 was merged.
