### ISSUE TITLE
Handle different server software versions

### ISSUE THREAD

**Issue by Ichimonji10** [SatelliteQE/automation-tools#179]
Satellite 6.0.7, 6.0.8 and 6.1.0 have been released, more releases will land in the future, and nightly builds are available too. Each version acts a little bit differently, and NailGun currently makes use of that versioning information when determining how to talk to the server. In addition, other parts of Satellite QE's software suite may make use of versioning information in the future. automation-tools should be updated to somehow make use of this versioning information. At the very least, version numbers should be passed to NailGun.

**Comment by elyezer** [comment]
Seems that Robottelo needs a configuration for this, and automation-tools can provide a task to identify the version information, then will configure Robottelo and finally NailGun.

**Comment by elyezer** [comment]
I think the only way to do this is by inspecting `/usr/share/foreman/lib/satellite/version.rb`

```
[root@qe-sat6-rhel71 ~]# cat /usr/share/foreman/lib/satellite/version.rb
module Satellite
  VERSION = "6.1.0"
```

I think maybe is better to add this as a helper on Robottelo as it already have a helper to identify if it is running against an upstream or downstream build.

**Comment by Ichimonji10** [comment]
That seems like a great solution to me.

**Comment by elyezer** [comment]
Closing this in favor of https://github.com/SatelliteQE/robottelo/issues/2414
