### ISSUE TITLE
Remove java workaround from rhel66 installation

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/automation-tools#187]
apparently this got fixed in Snap 7

**Comment by sghai** [comment]
With recent Snap7, the issue with jdk 1.8 is reproducible. So we need to keep the workaround until the bz 1216180  get fixed.

**Comment by sghai** [comment]
In Snap8, issue with openjdk 1.8 is fixed. we can remove the workaround now for rhel66

**Comment by elyezer** [comment]
Working on it.
