### ISSUE TITLE
Make sure that `non-authorized` proxy installation passes expected arguments to installer

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/automation-tools#188]
Yesterday I noticed that when I chose the `non-authorized` proxy configuration, even though the installation completed and I was able to use the system, whenever my `Satellite` system attempted to reach the `CDN` (after importing a manifest and trying to enable a Red Hat repository from the web ui), it would fail to reach it. I'm not sure if the `squid` server is at fault or not, but for what is worth, only the `port` and `url` flags were passed to the installer and not the `username` and `password`.

**Comment by elyezer** [comment]
The username and password is not being passed to the installer

```python
In [3]: r = urlsplit('proxy://example.com:3128')

In [7]: r.password is None
Out[7]: True

In [8]: r.username is None
Out[8]: True
```

In the code we have

```python
    if proxy_info.username is not None:
        installer_options['katello-proxy-username'] = proxy_info.username
    if proxy_info.password is not None:
        installer_options['katello-proxy-password'] = proxy_info.password
```

And running the task:

```
PROXY_INFO=proxy://example.com:3128 fab -H localhost setup_proxy
[localhost] Executing task 'setup_proxy'
[localhost] run: katello-installer -d -v --katello-proxy-url="http://example.com" --katello-proxy-port="3128"
...
```

**Comment by elyezer** [comment]
Closing this as it is not a automation-tool bug.
