### ISSUE TITLE
Task to fetch information for a Beaker job

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/automation-tools#200]
I want to start adding tasks that will allow us to handle `Beaker` tasks such as reserving systems, etc. So for starters, given a `Beaker` job `ID` I would like to get the `FQDN` for the system and its `status` (i.e. `Reserved`, `Running`, `Failed`, etc

**Comment by elyezer** [comment]
Please create a `beaker.py` module to place the new beaker related tasks.

**Comment by jhutar** [comment]
Mine plan is to have something with JobID as a parametr returning list of (job can involve more systems) dicts (to be able to extend which data should be returned) with content like:

[
  {'system': 'some.system.example.com', 'distro': '<RHEL-6.6>', 'variant': 'Server', 'arch': 'x86_64', 'status': 'Reserved'}
]

**Comment by jhutar** [comment]
Created this pull-request:

https://github.com/SatelliteQE/automation-tools/pull/201

**Comment by elyezer** [comment]
PR merged, closing this.
