### ISSUE TITLE
katello_service task fails on installation

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/automation-tools#217]
It looks like `katello-service restart` is run on the host rather than the sat vm.
```
[root@$autohost] run: katello-service  restart
[root@$autohost] out: bash: katello-service: command not found...
[root@autohost] out: 

Fatal error: run() received nonzero return code 127 while executing!

Requested: katello-service  restart
Executed: /bin/bash -l -c "katello-service  restart"
```

**Comment by sthirugn** [comment]
I tried https://github.com/SatelliteQE/automation-tools/pull/216 but did not work

**Comment by sthirugn** [comment]
this needs to be fix asap.

**Comment by omaciel** [comment]
You'll want to use `exec` when calling the method, and pass the host as an argument

**Comment by sthirugn** [comment]
ty @omaciel.  @elyezer fixed it now.

Previous:
```py
execute(katello_service('restart'), host=host)
```

After fix:
```py
execute(katello_service, 'restart', host=host)
```

**Comment by elyezer** [comment]
Was my fault, sorry. That product_install task is really hard to maintain, we definitely need to improve its maintainability.

**Comment by sthirugn** [comment]
No worries. All good now. Yeah we can definitely improve the tasks to differentiate between the parent host and the provisioned vms.
