### ISSUE TITLE
Investigate: automation-tools may be making bad assumptions about dhcp/dns interfaces

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/automation-tools#218]
In some cases (like when you've already set up virtual bridging on a target system), when running the installer via automation-tools, it sets default <code>--capsule-dhcp-interface</code> and <code>--capsule-dns-interface</code> to the virbr device.  This may not be entirely correct or the desired behavior.

I would think we would probably want to listen on whatever the default device is (e.g, eth0) rather than over the virtual bridge.  

Right now I don't *think* the current behavior is causing any issues, but it could in the future.

We need to investigate what the correct behavior should be, and if necessary, subsequently make changes to the logic automation-tools uses to determine proper interface.

**Comment by kbidarkar** [comment]
NOTE:
eth0 can only be used for RDULab kind of setup, when we are in an isolated subnet from dhcp point of view.
If we use eth0 , we will be hosting 2 dhcp server in the lab , conflicting.

If we ask the network team for dedicated VLAN/subnet for each of our Sat6 boxes, we can then use eth0.
