### ISSUE TITLE
User should be able to install Satellite from CDN based on user input either 6.0 or 6.1

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/automation-tools#220]
We should update CDN install task to cover both version based on user preference.

**Comment by elyezer** [comment]
:+1:

**Comment by sthirugn** [comment]
this is addressed in https://github.com/SatelliteQE/automation-tools/pull/222.  But this also needs jenkins update.

**Comment by sthirugn** [comment]
Jenkins update is done in https://github.com/SatelliteQE/robottelo-ci/pull/45
