### ISSUE TITLE
Add no.of tries or some timeout for assigning floating ip to instances

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#230]
https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L1766

At times we may face an issue with openstack unable to assgin floatin-ip's for whatever reasons.

The existing code looks to loop over infinitely till the instance get's an IP.  I think we need to add ' no.of try's' or 'timeouts' to avoid the loop.

**Comment by elyezer** [comment]
Any update on this?

**Comment by jyejare** [comment]
Yes the timeout in minutes has been implemented for assigning floating IP to the instance.
The PR #232 has been merged already.

Hence closing the issue.
