### ISSUE TITLE
If infiniband devices exists on physical hardware ignore errors for ifconfig

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#238]
Issue:
Looks like beaker provides machines which have inifiniband hardware adresses and results in the below error.

```
~]# ifconfig | grep virbr | awk '{print $1}'
Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
virbr1:
```

From man page of ifconfig
BUG: Ifconfig uses the ioctl access method to get the full address information, which limits hardware addresses to 8 bytes.  Because Infiniband hardware address has 20 bytes, only the first 8  bytes  are
       displayed correctly.  Please use ip link command from iproute2 package to display link layer informations including the hardware address.

**Comment by kbidarkar** [comment]
solution: Is to ignore the errors from ifconfig as we are only interested in picking up the virbr1 intefrace for configuring internal capsule.

Use the below command to make it compatible with infiniband hardware provided by beaker:
```
 ifconfig 2> /dev/null | grep virbr | awk '{print $1}'
```

**Comment by Ichimonji10** [comment]
Is there any reason we can't use `ip link` to get hardware addresses?

**Comment by kbidarkar** [comment]
Looks like the existing code used `ifconfig`, may be time move to 'ip link` . Looks like the below command would work.

`ip link show | grep virbr | awk '{print $2}' | head -n1`

**Comment by Ichimonji10** [comment]
That won't work quite like you expect. Here's some sample output from one of my systems:

```
$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 68:05:ca:01:20:a0 brd ff:ff:ff:ff:ff:ff
3: enp3s0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP mode DEFAULT group default qlen 1000
    link/ether b8:97:5a:04:f4:c8 brd ff:ff:ff:ff:ff:ff
4: wlp4s5: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc mq master br0 state UP mode DEFAULT group default qlen 1000
    link/ether 74:da:38:0d:9c:ef brd ff:ff:ff:ff:ff:ff
5: br0@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 74:da:38:0d:9c:ef brd ff:ff:ff:ff:ff:ff
6: tun0@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none
```

I can view information about only certain classes of devices:

```
$ ip link show type bridge
5: br0@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 74:da:38:0d:9c:ef brd ff:ff:ff:ff:ff:ff
$ ip link show type tun
6: tun0@NONE: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none
```

Some usages:

```
$ ip link show type bridge | awk '{print $2}' | head -n 1
br0@NONE:
$ ip link show | awk '{print $2}' | head -n 1
lo:
```

**Comment by elyezer** [comment]
Have run on a machine where we get that

```
# ip link show type bridge | awk '{print $2}' | head -n 1
Error: either "dev" is duplicate, or "bridge" is a garbage.
```

But `ip link show` lists all devices.

**Comment by kbidarkar** [comment]
@Ichimonji10 , `ip link show | grep virbr | awk '{print $2}' | head -n1`, works perfectly fine. You need to first configure the virtual bridge. It is at this stage the virtual bridge gets configured.

https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L257
```
run('puppet module install -i /tmp domcleal/katellovirt')
```

Or one can run this script to configure it, http://cosmos.lab.eng.pnq.redhat.com/rhel65/configure_libvirt.sh

```
networks]# cat /etc/libvirt/qemu/networks/foreman.xml 
<!--
WARNING: THIS IS AN AUTO-GENERATED FILE. CHANGES TO IT ARE LIKELY TO BE
OVERWRITTEN AND LOST. Changes to this xml configuration should be made using:
  virsh net-edit foreman
or other application using the libvirt API.
-->

<network>
  <name>foreman</name>
  <uuid>640c2af2-be6f-4c86-9376-b9cf084332c3</uuid>
  <forward mode='nat'/>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:xx:yy:zz'/>
  <ip address='192.168.100.1' netmask='255.255.255.0'>
  </ip>
</network>
```
