### ISSUE TITLE
Create manifest_download  function for downloading manifest from access.redhat.com

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/automation-tools#256]
I've already have a working `bash` and `python` script that authenticates on access.redhat.com and downloads the manifest for a specified `distributor`.
The site uses `SAML` for authorization.
![SAML](https://upload.wikimedia.org/wikipedia/en/thumb/0/04/Saml2-browser-sso-redirect-post.png/600px-Saml2-browser-sso-redirect-post.png)

- the required parameters used in my function are:
 - link to the resource site (access.redhat.com)
 - link to IDP
 - distributor hash (to identify registered satellite)
 - credentials

I wanted to start a discussion on how the function should look like (which parameters should be hardcoded and which required).
My idea is to start with a `config` dictionary, like:
```python
my_profile = {
    u'idp': u'https://fqdn.com/idp/',
    u'ugc': u'https://www.fqdn.com/wapps/ugc/',
    u'sso': u'https://www.fqdn.com/wapps/sso/',
    u'usr': u'foo',
    u'pwd': u'bar',
    u'dib': u'0000-0000-0000-0000-000000000000',
}
```

which will be passed to the 
```python
saml_authenticate(config=my_profile)
```
for the download itself, I would suggest to create a standalone function, calling `rhn_authenticate` inside:
```python
def download_manifest(filepath, config=None):
    if config is None:
        raise ValueError, 'Config dictionary needs to be passed'
    session = saml_authenticate(config)
    with open(filepath, 'wb') as file:
        manifest = session.get(
            'https://<fqdn>/management/distributors/'
            '{}/certificate/manifestdownload'.format(config['dib']),
        )
        if not manifest.ok:
            print('GET request failed')
        for block in manifest.iter_content(1024):
            file.write(block)

```
Any comments/thoughts/suggestions would be appreciated.

**Comment by lpramuk** [comment]
Great work, Roman reverse_engineering++

saml_authenticate(config=my_profile)
- doesn't need all keys from config, lets give it only params that are actually needed (idp,ugs,sso)

**Comment by lpramuk** [comment]
IMO we can consider information such as "access.redhat.com", IDP server, SSO + UGC server public
Coz evryone can fetch these url by just looking into HTTP headers... WYT? (can go on github)

**Comment by lpramuk** [comment]
@omaciel @elyezer  What approach we decided to use here?
A seperate cron script   vs.    part of automation tools?

If download from Customer Portal fails for whatever reason, then sesame should act as a failsafe backup source...

**Comment by oshtaier** [comment]
It will be nice if we don't hardcode things like this:
```
my_profile = {
    u'idp': u'https://fqdn.com/idp/',
    u'ugc': u'https://www.fqdn.com/wapps/ugc/',
    u'sso': u'https://www.fqdn.com/wapps/sso/',
    u'usr': u'foo',
    u'pwd': u'bar',
    u'dib': u'0000-0000-0000-0000-000000000000',
}
```
and put let's say by default:
my_profile = {
    u'idp': u'https://fqdn.com/idp/' (or None in case it is sensitive data),
    u'ugc': u'https://www.fqdn.com/wapps/ugc/'(or None in case it is sensitive data),
    u'sso': u'https://www.fqdn.com/wapps/sso/'(or None in case it is sensitive data),
    u'usr': None,
    u'pwd': None,
    u'dib': None,
}

and each user provide that data by himself to be isolated from all people

**Comment by elyezer** [comment]
Passing dictionaries to fab is not easy, can you please add parameters to the download function?

Like:

```python
def download_manifest(filepath, idp_url, ugc_url, sso_url, user, password, distributor_id):
```

**Comment by rplevka** [comment]
@elyezer: :+1: 

@oshtaier: sure, that dictionary was not meant to be hardcoded in the `download_manifest` method.

As @elyezer proposed, we'll accept individual parameters.

@lpramuk: yeah, thanks for comment. I'll probably put the redhat urls into a docstring as an 'example'

**Comment by rplevka** [comment]
So there we go:
https://github.com/SatelliteQE/automation-tools/pull/260

**Comment by kbidarkar** [comment]
We also have added a `Satellite6-manifest-downloader` job to jenkins.
https://github.com/SatelliteQE/robottelo-ci/pull/109

**Comment by rplevka** [comment]
Since all the related PR's are merged, I'm closing this.
