### ISSUE TITLE
Reboot vm after satellite install

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/automation-tools#258]
From https://github.com/SatelliteQE/robottelo/issues/2906

**Comment by jyejare** [comment]
Please explain more about this issue.

**Comment by elyezer** [comment]
A machine reboot should be performed whenever the Satellite installation is completed.

**Comment by elyezer** [comment]
@jyejare does the above make it clear?

**Comment by kbidarkar** [comment]
With the new reset+snapshot feature added, I think this is no longer needed as we now reboot between each Tier.

**Comment by elyezer** [comment]
@kbidarkar good point, yeah if that is restarting the machine then we are fine.

**Comment by kbidarkar** [comment]
1) Upgrade: After installing satellite6 packages, we do reboot for upgrade.https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/satellite6/upgrade/satellite.py#L126 

2) Satellite jobs: With the reset+ snapshot changes this is fixed now.
