### ISSUE TITLE
Reboot satellite and capsule during upgrade automation.

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#261]
We have found some issues when we reboot satellite and capsule during upgrade process, so need to add this in our upgrade automation.
Following things are required to do:
1. Satellite:
      i) Reboot after first yum update
     ii) Reboot before satellite upgrade (i.e before execution katello-installer --upgrade)
2. Capsule:
      i) Reboot after first yum update
     ii) Reboot before capsule upgrade (i.e before execution capsule-installer --upgrade --certs-tar <capsule_certs_tar_file_path> )

**Comment by elyezer** [comment]
Fabric provides a `reboot` function. It may work:

```
Signature: reboot(*args, **kwargs)
Docstring:
Reboot the remote system.

Will temporarily tweak Fabric's reconnection settings (:ref:`timeout` and
:ref:`connection-attempts`) to ensure that reconnection does not give up
for at least ``wait`` seconds.

.. note::
    As of Fabric 1.4, the ability to reconnect partway through a session no
    longer requires use of internal APIs.  While we are not officially
    deprecating this function, adding more features to it will not be a
    priority.

    Users who want greater control
    are encouraged to check out this function's (6 lines long, well
    commented) source code and write their own adaptation using different
    timeout/attempt values or additional logic.

.. versionadded:: 0.9.2
.. versionchanged:: 1.4
    Changed the ``wait`` kwarg to be optional, and refactored to leverage
    the new reconnection functionality; it may not actually have to wait
    for ``wait`` seconds before reconnecting.
File:      ~/.virtualenvs/automation-tools/lib/python2.7/site-packages/fabric/network.py
Type:      function
```

**Comment by elyezer** [comment]
Will add this note [1] here just as informative for folks that are looking for playing with Ansible.

cc: @cswiii @omaciel 

[1] https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back

**Comment by jyejare** [comment]
Currently PR #268 satisfies the requirement for temporary purpose. Will look into solid reboot technique in nearby feature.

**Comment by sthirugn** [comment]
@jyejare can you check and close this issue? I think all reboot requirements are in place.

**Comment by jyejare** [comment]
@sthirugn , Yes the reboot methods needs an improvement and i m currently in that process. The current method is very basic and logicless.

**Comment by jyejare** [comment]
I wanted to have some solid reboot method but we if the satellite machine is running as VM then its hard to get the status during reboot(e.g: some vm's on CR's pings to ip even its rebooting) and the method for getting the reboot status is different for every compute resource. So as of now keeping the current reboot method with fix wait time as unique for them all.

If you have any idea which is unique for all the compute resource, please raise a new issue.
