### ISSUE TITLE
Task install_puppet_scap_client fails when installing Satellite6.0

### ISSUE THREAD

**Issue by rwilliams5** [SatelliteQE/automation-tools#267]
product_install task fails to install package puppet-foreman_scap_client. Looks like this package does not exist within the repos set for satellite6.0.

Maybe there should be a check around this task depending on the OS version?

**Comment by omaciel** [comment]
@rwilliams5 yeah, iirc there is no `puppet-foreman_scap_client` for RHEL 6 so a check here would make sense. @elyezer ?

**Comment by elyezer** [comment]
I will work on this. Thanks @rwilliams5 for the report.

**Comment by kbidarkar** [comment]
There is no such package for Satellite6.0 , but only from Sat6.1 ( only downstream, upstream needs a tar file I believe) . Need to investigate in detail further. Will do.

**Comment by rplevka** [comment]
https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L1148
this is the place we trigger `oscap client` installation. We do not check which version of satellite 6 is being installed. We need to add a conditional to trigger this only if `6.0` is being installed
