### ISSUE TITLE
create a Wrapper for running the hammer commands in Upgrade with prefixes.

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#269]
create a wrapper for run, something like run_prefix() in which you can prefix initials = 'hammer -u admin -p {0} '.format(admin_password) and run it. This will avoid using initials+ every time.

From: https://github.com/SatelliteQE/automation-tools/pull/268/files#r46311070

**Comment by elyezer** [comment]
We already have this in place for capsule module https://github.com/SatelliteQE/automation-tools/blob/4a3f650fb33d402845881d6417966a13f1ca1cd9/automation_tools/satellite6/capsule.py#L275. Seems that now is time to find a proper place to have that that.

**Comment by jyejare** [comment]
I can surely use that @elyezer. I will find a time to repair that.

**Comment by jyejare** [comment]
Closing this issue as new hammer wrapper and new hammer module is created in automation-tools.
