### ISSUE TITLE
katello installer should run with dhcp-range option while setting up default capsule

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/automation-tools#270]
Currently, we are running katello-installer without `--capsule-dhcp-range` option. However it is required for host discovery. Without this option, a pxe boot host won't get IP from dhcp server.

I think setting environment variable `dhcp_range` in jenkins -> Provisioning Env variables should solve the issue.

**Comment by kbidarkar** [comment]
The PR is referenced above and we now also have the same support for even satellite6-installer robottelo-ci#110
