### ISSUE TITLE
Add upgrade test from 6.0.8 to latest

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/automation-tools#283]

**Comment by jyejare** [comment]
Actually, Our automation already supports from 6.0.8 to latest. The only thing is that I have to create an images on openstack.

**Comment by jyejare** [comment]
The issue identified when installing 6.0.8 on RHEL 71. So need to install it on RHEL 71 and while upgrading OS to RHEL 72 as well as Satellite to 6.1. That is something need to work on.

**Comment by jyejare** [comment]
@omaciel @cswiii , Are we really supporting this path from 6.0.8 to 6.2 ?

**Comment by omaciel** [comment]
@jyejare seems that @cswiii has replied to you via email. Can you confirm it?

**Comment by jyejare** [comment]
There is no direct upgrade from 6.1 to 6.2.
The customer has to upgrade 6.0 to 6.1 first and then 6.1 to 6.2.

**Comment by elyezer** [comment]
@jyejare I see two different jobs here, one to update from 6.0 to 6.1 and then from 6.1 to 6.2. We may lose something by not walking though the complete path but it seems not practical to have it covered since we may end up having a path like 6.0 -> 6.1 -> 6.2 -> 6.3 -> ...

That said I will ask @omaciel, @sthirugn and @cswiii opinion in here. We need to find the best position in between having a good upgrade coverage and maintainability of the jobs.

**Comment by jyejare** [comment]
ping @omaciel , @cswiii  and @sthirugn.

**Comment by omaciel** [comment]
I agree with @elyezer that there are 2 paths:
* 6.0 > 6.1.x
* 6.1.x > 6.2.x

With that said, I don't know how much longer we will be supporting upgrades from 6.0. @cswiii ?

**Comment by mccun934** [comment]
what @jyejare said, we do not support upgrading from 6.0 to 6.2 in one operation.

You have to go from 6.0 -> 6.1 and then 6.1 -> 6.2

We will support upgrades from 6.0 to 6.1 in perpetuity as long as we are still shipping the software.

**Comment by sghai** [comment]
Our Jenkins upgrade installer job is flexible enough to support both paths (6.0 -> 6.1 and 6.1 -> 6.2). But trigger just perform upgrade from 6.1 -> 6.2. 

@jyejare : Please add if I missed something.

**Comment by jyejare** [comment]
@sghai, Thats True ! 
@cswiii @omaciel @sthirugn 
We have Standalone installer job to upgrade from 6,0 to 6.1 and then 6.1 to 6.2.
Also we don't have upgrade trigger job for upgrading from 6.0 to 6.2 as we are not testing for every snap or compose.

With that said I am closing this issue in favour of standalone job. Still if you feel that has to be added in trigger we will create a new issue for that.
