### ISSUE TITLE
Disable 'extras' repository after installing Docker on RHEL 7 systems

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/automation-tools#310]
We should add another command after [this](https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L195) to make sure that we disable the 'extras' repository after installing Docker on RHEL 7 systems. Note that we do that already for RHEL 6 systems.

The new line should be:

```python
        run(
            'subscription-manager repos --disable "rhel-{0}-server-extras-rpms"'
            .format(os_version)
        )
```

**Comment by omaciel** [comment]
@elyezer assigned this to @rochacbruno :)

**Comment by rochacbruno** [comment]
@omaciel I used the existing **disable_repos** function which does exactly the same. Now I am just going to call some @elyezer 's help to test it and then send a PR.

**Comment by rochacbruno** [comment]
@omaciel PR sent #312
