### ISSUE TITLE
Better environment variable parsing for INSTALLER_OPTIONS

### ISSUE THREAD

**Issue by elyezer** [SatelliteQE/automation-tools#313]
Installer options parsing should happen as soon as possible on `product_install` task in order to fail without doing any action on the server.

```
    if os.environ.get('INSTALLER_OPTIONS'):
        # INSTALLER_OPTIONS are comma separated katello-installer options.
        # It will be of the form "key1=val1,key2=val2".
        ins_opt = os.environ.get('INSTALLER_OPTIONS', '')
        ins_opt_dict = dict(i.split('=') for i in ins_opt.split(','))
        installer_options.update(ins_opt_dict)
```

**Comment by elyezer** [comment]
Actually it is not a bug, but an enhancement. Updated the labels to match that.

**Comment by lpramuk** [comment]
@elyezer Why to fail ? rather continue without unparsable options...

**Comment by elyezer** [comment]
@lpramuk because the user was asking for something and the system decided to go with a subset of what has been asked. Better to tell the user that is wrong than deciding what is best to do...

**Comment by san7ket** [comment]
Currently satellite adds in installer options against all the plugins installed and supported. This is very hard to keep track of,. Also, the error reporting of the installer itself as drastically improved. So, the tasks fails quickly, and user can easily figure out what went wrong. 

Please feel free to re-open, if this still needs fixing
