### ISSUE TITLE
Add packages needed for SCAP functionality (policies, content, reports)

### ISSUE THREAD

**Issue by oshtaier** [SatelliteQE/automation-tools#323]

**Comment by elyezer** [comment]
What are the needed packages? If you already this information is better to list it here.

**Comment by kbidarkar** [comment]
a) By just running `satellite-installer` we can now install the needed packages for OSCAP
b) Also the following PR's #350, #349, #353  should fix this issue for Satellite6.2.

Closing this issue now, Please feel free to Re-open this issue if this appears broken.
