### ISSUE TITLE
Fix capsule upgrade command with 6.2 command

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#355]
Fix  closed PR #352.

**Comment by elyezer** [comment]
What exactly is not working there? When opening issues is better to provide more details specially for others like me :smile: that follows the updates on the issues and PRs.

**Comment by jyejare** [comment]
@elyezer Actually @sthirugn updated capsule upgrade related fix in old upgrade automation code which is now fixed in PR #356 and also the old code has been removed.

**Comment by elyezer** [comment]
@jyejare thanks for the clarification. Since the referenced PR is merged can we close this?

**Comment by jyejare** [comment]
Yes ! Closing this issue as PR #356 is merged.
