### ISSUE TITLE
Upstream installer does not install plugins which are included in Satellite

### ISSUE THREAD

**Issue by rplevka** [SatelliteQE/automation-tools#391]
According to our upstream automation and `standalone installer` jobs, installed katello (satellite-upstream) doesn't have plugins installed (discovery, libvirt, etc.) which causes our tests to fail.

I believe we consider `upstream` Katello with all plugins which are bundled together and installed by default in Satellite 6 therefore I'm marking this issue as a bug

**Comment by lpramuk** [comment]
Yes, seems to me correct as we need to test also non-default upstream features which eventually land downstream to detect problems in advance.

**Comment by lpramuk** [comment]
Let's start by omitting:
- https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L1254-L1255 to have default smart proxy set up
- https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L1325 to have oscap_content, setup_foreman_discovery, enable_ostree being run

**Comment by lpramuk** [comment]
We need to install additional packages ```foraman-libvirt```, ```foreman-openstack``` ... after this command:
https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L959-L963

**Comment by kbidarkar** [comment]
I think this is not a bug, but rather it was done intentionally by many folks, which I am not sure why?
But we definitely need these.

Also setup for upstream is different than that of downstream.

At-least in my case, For example, OSCAP: Only downstream package exist , there is a puppet-module which needs to be used for upstream. These need to be handled differently.

Such issues could exist for other features too, which needs to be investigated.

**Comment by sghai** [comment]
Yeah.. That's what I mentioned in our last automation meeting for Discovery too. The setup for discovery is bit different from downstream. I'll retry discovery as part of new release 7.0 and come up with a solution for upstream.

**Comment by lpramuk** [comment]
Discovery is broken currently therefore I need some "iffing" based on bz/redmine statuses -> therefore opened new issue #394 for bz/redmine support in automation-tools

**Comment by rochacbruno** [comment]
@lpramuk the following error are related to this issue?

Jenkins upstream provisioning job
```
[10.8.29.163] Executing task 'setup_satellite_firewall'
rhel 7 2
[10.8.29.163] run: systemctl enable firewalld
[10.8.29.163] out: Created symlink from /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service to /usr/lib/systemd/system/firewalld.service.
[10.8.29.163] out: Created symlink from /etc/systemd/system/basic.target.wants/firewalld.service to /usr/lib/systemd/system/firewalld.service.
[10.8.29.163] out: 

[10.8.29.163] run: systemctl start firewalld
[10.8.29.163] run: for port in $(firewall-cmd --permanent --list-ports); do firewall-cmd --permanent --remove-port="$port"; done
[10.8.29.163] out: Error: INVALID_ZONE
[10.8.29.163] out: Error: INVALID_ZONE
[10.8.29.163] out: 

Fatal error: run() received nonzero return code 112 while executing!

Requested: for port in $(firewall-cmd --permanent --list-ports); do firewall-cmd --permanent --remove-port="$port"; done
Executed: /bin/bash -l -c "for port in \$(firewall-cmd --permanent --list-ports); do firewall-cmd --permanent --remove-port=\"\$port\"; done"

Aborting.
```

**Comment by rochacbruno** [comment]
@lpramuk also

Standalone installation on a beaker box
```
run: systemctl enable libvirtd
rhel 7 2
run: systemctl start libvirtd
run: puppet module install -i /tmp domcleal/katellovirt
out: Notice: Preparing to install into /tmp ...
out: Notice: Downloading from https://forgeapi.puppetlabs.com ...
[intel-lizardhead-02.lab.bos.redhat.com] out: Error: Could not connect to https://forgeapi.puppetlabs.com
out:   There was a network communications problem
out:     The error we caught said 'getaddrinfo: Name or service not known'
out:     Check your network connection and try again
out: 

Fatal error: run() received nonzero return code 1 while executing!

Requested: puppet module install -i /tmp domcleal/katellovirt
Executed: /bin/bash -l -c "puppet module install -i /tmp domcleal/katellovirt"

Aborting.
```

**Comment by rochacbruno** [comment]
I tried to rebuild but got

```
run: hammer -u admin -p ******* template update --name "PXELinux global default" --file /tmp/tmp.FkhgsnJZ3r
out: Could not update the config template:
out:   This template is locked. Please clone it to a new template to customize.
out: 

Fatal error: run() received nonzero return code 65 while executing!

```

Not sure if this is related to the issue
