### ISSUE TITLE
Make sure ovirt-engine-sdk-python can be used of the latest version for upgrade testing

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#396]
1) Ovirt sdk version got updated and broke our automation.
2) https://pypi.python.org/pypi/ovirt-engine-sdk-python   ( 4.0.0 released on 2016-08-30 )
3) Currently raised a PR to freeze the version, https://github.com/SatelliteQE/automation-tools/pull/395

We need to get upgrade testing work with 4.0.0

**Comment by jyejare** [comment]
@kbidarkar Cool, Yesterday I noticed that and proposed that fix in my PR which yet to be merged. But thanks for raising the PR fix it immediately.

**Comment by lpramuk** [comment]
didn't we pinned it? https://github.com/SatelliteQE/automation-tools/blob/master/setup.py#L26

I thought that version of this package should match version of RHEVM (3.6) we are controlling (client version should match server version)

Once we had RHEVM 4.0 we would use ovirt-engine-sdk-python 4.0.0 ...

**Comment by kbidarkar** [comment]
Ok, in that case this is not needed.
