### ISSUE TITLE
Perform 1000+ Client install and upgrade using Dockerized image.

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#401]
Perform 1000+ clients installation and upgrade using jcallahan's dockerized cent-os images.

**Comment by sghai** [comment]
Just a suggestion, it would be good if we use `RHEL` images instead of `CentOS`

**Comment by jyejare** [comment]
@sghai I searched docker hub and I dont see any official docker image for redhat. @JacobCallahan Do you have any idea about that ? 

OR else Shall I move with CentOS image ?

**Comment by JacobCallahan** [comment]
We've got a few options here. We can continue with the image that I have been using. Or we can use a custom-built image that I've also started prepping. I can continue more work on the second option after this stream is completed.

**Comment by elyezer** [comment]
Docker images for RHEL can be found at the Red Hat registry. I don't know what is needed in order to access the images but they need to be tweaked in order to be an useful image. Check Red Hat's documentation for docker images and you will find more information.

**Comment by sghai** [comment]
@jyejare : As @elyezer pointed, you can get RHEL images from Red Hat registry. Even if you pull that  from internal registry then you have to keep your customized images internal only, may be on your own internal registry. You can not publish them on docker hub.

**Comment by jyejare** [comment]
Also the reorg of upgrade modules(module for each satellite, capsule and client) is going to happen.

**Comment by kbidarkar** [comment]
Fixed in #429
