### ISSUE TITLE
add optional-rpms to repofile_install for rhel6

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#416]
currently the repo appears to exists for RHEL7 only.

Track/Investigate and add support for RHEL6 too.

**Comment by lpramuk** [comment]
# subscription-manager repos --enable rhel-*-server-optional-rpms
Repository 'rhel-6-server-optional-rpms' is enabled for this system.

**Comment by kbidarkar** [comment]
Looks like the actual stuff that we need here is installation of `grub2-efi-modules` package for optional-rpms from rhel6. Last time I checked, I couldn't find the repo, had to investigate this further.

**Comment by kbidarkar** [comment]
Discussions and explanation for this exists in PR #425
