### ISSUE TITLE
Fix automation-tools to use satellite_version==nightly , rather than distribution==upstream

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#422]
1) Fix all the instances of distribution==upstream with satellite_version==nightly 
2) This will help with consistency

**Comment by lpramuk** [comment]
I'm also in favor of ```satellite_version == 'nightly'``` instead of ```distribution == 'upstream'

by ```satellite_version``` we say WHAT to install (6.2 6.3 nightly)
by ```distribution``` we say the WAY to install (internal, cdn, repofile...)

**Comment by kbidarkar** [comment]
Fixed in , https://github.com/SatelliteQE/automation-tools/pull/431
