### ISSUE TITLE
enable_ostree task fails for machine with < 8GB memory 

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/automation-tools#423]
```
Executing task 'enable_ostree'
rhel 7 2
[fqdn] run: satellite-installer --scenario satellite --katello-enable-ostree=true
[fqdn] out: This system has less than 8 GB of total memory. Please have at least 8 GB of total ram free before running the installer.
[fqdn] out: 

Fatal error: run() received nonzero return code 1 while executing!

Requested: satellite-installer --scenario satellite --katello-enable-ostree=true
Executed: /bin/bash -l -c "satellite-installer --scenario satellite --katello-enable-ostree=true"

Aborting.
```
Even if you specify in jenkins ```INSTALLER_OPTIONS [disable-system-checks]``` the main installer is run with them but later on during plugin enablement it forgets about ```--disable-system-checks``` and fails to enable it (on machine with less than 8GB of memory)

**Comment by lpramuk** [comment]
I would add ```--disable-system-checks``` explicitly as this options seems to be not remembered for next installer runs (which is intention and not a bug...imo)

**Comment by lpramuk** [comment]
Note: Noway I'm using machine with low memory for testing. But consider this machine:
```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           7.6G        3.4G        870M         34M        3.4G        3.8G
```
we have a lot of such machines in our testing pool i.e. having slightly below 8G of mem.
The reason is that 8G is dedicated but virtualization overhead takes up some chunk of memory, depending on OS (~ 250M)

**Comment by omaciel** [comment]
@lpramuk @kbidarkar  I am closing this due to #424 getting merged.
