### ISSUE TITLE
Enable flake8 run via travis for automation-tools

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#426]
I want to focus on code rather than remembering to run this each time I change something, if travis build fails, would like to fix it ASAP.

**Comment by kbidarkar** [comment]
I am new to this, will check it out and fix it, in the meantime if anyone wants to enable it, please feel free to add this.

**Comment by rochacbruno** [comment]
@kedar I can do that, I'll send a PR including flake8 on travis and also some make targets to help locally. (commit hook)

**Comment by rochacbruno** [comment]
@kbidarkar travis is now enabled by @omaciel, in #428 I added `make install-commit-hook` so you can run it only once locally and then every time you commit flake8 errors will be checked before commiting.
