### ISSUE TITLE
Reboot the Sateliite after upgrading OS

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#442]
As per Email Thread comments:
```
Folks doing rhel upgrade testing: Can you please incorporate this scenario in the test plan for future? Thanks!

Scenario:
- Install rhel 6.x or 7.x
- Install Satellite latest
- Upgrade to rhel 6.x+1 or 7.x+1
- Reboot
- Make sure Satellite is functional.
```

Implement - Reboot satellite after upgrade.

**Comment by sghai** [comment]
@jyejare: Lets move this to satellite6-upgrade if its still an issue ?

**Comment by jyejare** [comment]
@sghai , If we look at the description of this issue, it looks like we have covered this in satellite-clone in migration phase.
Please confirm the same.

**Comment by sghai** [comment]
I think its reboot post upgrade.. not related to migration

**Comment by jyejare** [comment]
@sghai , Yeah ! We are upgrading OS(in case of next z vsrion is available) and rebooting also. But we are not doing that last part ```Make sure Satellite is functional.```.

It looks like a separate test which is not related to satellite upgrade. The word functional has so much things in it. And I am really not sure How can we achive this with Satellite6 upgrade project.

**Comment by sghai** [comment]
Yeah.. that's fine.. we can close out as we are already running tier1 tests post upgrade..

**Comment by jyejare** [comment]
But the upgrade of OS is happening on old version of satellite and we are running tier tests after upgrade to latest. So here,
1. We cannot test the functional after reboot scenario as we cant run tier tests on prevoius version.
2. We cannot test the functional after upgrade as reboot happened on previous version.

**Comment by san7ket** [comment]
Please feel free to re-open, if this still needs fixing
