### ISSUE TITLE
Make switching between AK to REPOFILE install method possible

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#443]
If for some reason we may want to move from AK to REPOFILE install method, 
one needs to run the below commands.

1) subscription-manager unregister
2) subscription-manager clean 
3) fab -H root@fqdn-hostname clean_rhsm
4) Remove any *.repo files in /etc/yum.repos.d/
5) yum clean all
6) Rebuild using REPOFILE

**Comment by lpramuk** [comment]
You may miss ```sed -i 's|^repo_ca_cert\s*=.*|repo_ca_cert = %(ca_cert_dir)sredhat-uep.pem|' /etc/rhsm/rhsm.conf```

**Comment by lpramuk** [comment]
We need to have such cleanup at start to be able to re-run any installations (currently we can unless we dont mix them  - AK vs. others)
