### ISSUE TITLE
Recreate Satellite and Capsule Templates/Images on RHEVM

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#444]
**This is a very high priority issue:**
We have recently changed capsule configuration(specially Domain) to make completely Isolated capsule. And hence the capsule hostname is been changed:
RHEL7:
From - qe-capsule-rhel7.satqe.lab.eng.rdu2.redhat.com
To - qe-capsule-upgrade-rhel7.capqe.lab.eng.rdu2.redhat.com
RHEL6:
From - qe-capsule-rhe6.satqe.lab.eng.rdu2.redhat.com
To - qe-capsule-upgrade-rhel6.capqe.lab.eng.rdu2.redhat.com

So to update this changes **we need to completely recreate the images for casule** and **this capsule will be added to our existing Satellite images, so Satellite Images also needs to be updated**.

**Comment by omaciel** [comment]
@jyejare who will or should work on this task?

**Comment by jyejare** [comment]
@omaciel , I am working on it with the help of @kbidarkar on networking issues. Currently I am facing issues removing previous capsule, hosts on that capsule etc  as the capsule entry doesnt exists anymore in DNS.

**Comment by kbidarkar** [comment]
It is better we recreate both satellite and cpasule images, as we may face issues later on.
The idea here is to test upgrade procedure with external capsule as isolated as possible and hence was the change in domainname of the capsules.

@jyejare , I believe we have enough time available with us to recreate the images for both satellite and capsule and keep things ready for next upgrade. I feel feature owners may help in populating the templates here with various features.

I can help on populating the sat and cap , images with my features which I used to work on, along with @san7ket .

**Comment by sghai** [comment]
@omaciel : I'm working on a spreadsheet and with that we can track all the required efforts. I'll outline are required tasks and will share with everyone soon.

**Comment by san7ket** [comment]
As this is a big task , with numerous sub-tasks to do, using this issue as a tracker for all the sub-tasks.
Completed , #454 
Note: Details in spreadsheet

**Comment by san7ket** [comment]
Completed , Template for Satellite 6.0 ready #461

**Comment by san7ket** [comment]
New Images are created and is used by upgrade automation. Closing this..
