### ISSUE TITLE
Unify / Simplify *_install() methods

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/automation-tools#445]
Please see my https://github.com/SatelliteQE/automation-tools/pull/437#issuecomment-258391015 for the idea
```
if distro=satellite6-activationkey:
    subscribe_dogfood()
else:
    subscribe()

<--- here we can continue unified  

install_prerequisites()
set_yum_debug_level()
update_packages()
```

**Comment by lpramuk** [comment]
another reason is that:
os_upgrade_repo ```execute(create_custom_repos, rhel_candidate=os_upgrade_repo, host=host)``` needs to run after ```execute(install_prerequisites, host=host)```
(broken by PR https://github.com/SatelliteQE/automation-tools/pull/436)

**Comment by elyezer** [comment]
#446 is merged. I think we can close this.
