### ISSUE TITLE
Log analyzing Tool while Upgrade Running

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#447]
Implement / Come up with Log analyzing tool while Upgrade in progess/running, which will:
1. Alert if Error/Exception observed in bg logs
2. Save/Collect all the logs for debugging the failures later

**Comment by sghai** [comment]
@renzon :Could you please take this up and see if we can come up with some automated solution to analyze execptions/errors from different log files. We can discuss the issue in detail.

**Comment by sghai** [comment]
I think following log files needs to be analyzed.

```
/var/log/foreman-installer/satellite.log
/var/log/foreman/production.log
/var/log/foreman-proxy/proxy.log
/var/log/candlepin/candlepin.log
/var/log/messages
/var/log/mongodb/mongodb.log
/var/log/tomcat/catalina.out
```
