### ISSUE TITLE
For openstack provisioning we need to run the installer to add muliple zones

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/automation-tools#474]
a) The openstack currently being used by qe is in a new domain so it needs to updated in /etc/zones.conf file
b) Run, satellite-installer --foreman-proxy-dns-zone  "xyzt.com"
And due to the subnet of "x.y.z.0/22" did the below.
c) Run, satellite-installer --foreman-proxy-dns-reverse "x.y.z.in-addr.arpa"
d) Run, satellite-installer --foreman-proxy-dns-reverse "x1.y.z..in-addr.arpa"
e) Run, satellite-installer --foreman-proxy-dns-reverse  "x2.y.z..in-addr.arpa"
f) Run, satellite-installer --foreman-proxy-dns-reverse "x3.y.z..in-addr.arpa"

**Comment by kbidarkar** [comment]
This below PR should be taking care of all the things from a) to f).
https://github.com/SatelliteQE/automation-tools/pull/516
Also, this PR clones and updates the `Satellite6 kickstart default finish` template to include the `sshkey parameter`.
