### ISSUE TITLE
LogAnalyzer: Redirect full logs to a directory with separate log files

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#479]
Redirect the full Logs to a Directory having log files for every log file of system.

**Comment by renzon** [comment]
@jyejare

**Comment by jyejare** [comment]
@renzon , I think we can create a folder from python in executing directory(automation-tools) and later we can publish that directory as artifact of jenkins-job.
What to you think @sghai , @kbidarkar & @elyezer ?

**Comment by sghai** [comment]
Yeah +1 to @jyejare.

**Comment by elyezer** [comment]
Make sure to have this directory within the job workspace and also to clean it after archiving.
