### ISSUE TITLE
Upgrade Automation collecting Foreman-Debug logs two times

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#508]
It looks,

Upgrade Automation collecting foreman debug logs when 'Upgrade Passed on Console ' and 'Errors in logs of Upgrade '.

Collection should be only once in any case.

**Comment by renzon** [comment]
@jyejare Do you have the console output so I can better understand the issu?

**Comment by jyejare** [comment]
Closing this issue as I am unable to repro in recent past.  I will reopen the issue if I come across in our new uprade automation project.
