### ISSUE TITLE
Upgrade tasks - needs to be performed w/ rhev templates

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/automation-tools#513]
- [x] Images needs to be updated so that all manifest tests/RHEL repo enabling tests should succeed

- [x] Run this task once `setup_alternate_capsule_ports`

- [x] Create rhev_template task so that we can create templates via rhev api's

**Comment by sghai** [comment]
First two tasks required to improve the tier1 test results post upgrade.

**Comment by sghai** [comment]
Third one related to `rhev_template` is required to re-create the template everytime a new version is released. We may add this as conditional check w/ `satellite6_upgrader` job. If the create_template check is enabled, the job itself will do a sanity check post-upgrade and creates the templates w/ newly released version.

Please feel free to either create new tasks or consider this task as a tracker.

**Comment by sghai** [comment]
For first task, this needs to be run on upgrade instances:  https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/__init__.py#L399

**Comment by san7ket** [comment]
The tasks for the creating rhev template, is merged. But blocked on creating a job for this , unless we get a mechanism to handle the paused and errored tasks. We can still use "fab" to run the task, So we could say we have a partial automation around this.

**Comment by san7ket** [comment]
Closing this ,as the PR is merged
