### ISSUE TITLE
6.1> 6.2 Capsule upgrade forgets to enable 6.2 capsule repo

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/automation-tools#515]
From upgrader job no 539:

```
[capsule_hostname] run: subscription-manager repos --disable "rhel-6-server-satellite-capsule-6.1-rpms"
[capsule_hostname] out: Repository 'rhel-6-server-satellite-capsule-6.1-rpms' is disabled for this system.
[capsule_hostname] out: 

[capsule_hostname] run: yum repolist
[capsule_hostname] run: yum clean all
Wait till packages update ... 
YUM UPDATE started at: Tue Feb 21 12:17:01 2017
[capsule_hostname] run: yum update -y 
```

6.1 capsule repo is disabled but  the 6.2 version is not enabled instead, and the process continues straight to yum update, which causes the overall capsule upgrade to fail due to missing pkgs. I think the code to be enhanced is here https://github.com/SatelliteQE/automation-tools/blob/master/automation_tools/satellite6/upgrade/capsule.py#L93

**Comment by san7ket** [comment]
Please feel free to re-open, if this still needs fixing
