### ISSUE TITLE
Still annoying yum logs are disturbing client upgrade

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#553]
Same issue as : #541.

**Comment by jyejare** [comment]
Need to investigate on 'wait untill yum lock available' and remove the existing approach of hard sleep time.

**Comment by san7ket** [comment]
Also needed for issue https://github.com/SatelliteQE/automation-tools/issues/532

**Comment by jyejare** [comment]
The issue has been fixed with PR #579
