### ISSUE TITLE
Fix org name in upgarde boxes 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/automation-tools#555]
In 6.1 the default org was Default_Organization which was updated in 6.2 as Default Organization and our tier1 tests uses the same.

**Comment by jyejare** [comment]
What fix you want ? in images ? or in code ?

**Comment by sghai** [comment]
In Sat 6.0, the default org name was `Default_Organization` however in 6.1 and 6.2 the default org name changed to `Default Organization`.

So I think we can fix the failed tests by updating the org name from `Default_Organization` to `Default Organization` but first need to check if it has any side effects or will it affects any functionality etc ?

And, If org updates works w/o affecting any existing functionality then I think we can simply run the hammer command to update org before running post upgrade tier1 tests.

What you guys think ?

**Comment by san7ket** [comment]
yep , I am ready with the PR , 
As of now, I think it does affect any functionality.

**Comment by san7ket** [comment]
https://github.com/SatelliteQE/automation-tools/pull/556

**Comment by sghai** [comment]
@san7ket : I believe you wanted to say that it doesn't affect any functionality right ?

**Comment by san7ket** [comment]
PR merged.
