### ISSUE TITLE
Randomly client upgrade fails, when done with docker containers

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/automation-tools#585]
Currently, same docker vm is used to create , containers for rhel6 and rhel7 upgrade. These upgrades when ran concurrently, may result in deletion of containers created by each other. 
Solution: We can create a clean-up job which can be run periodically to delete these containers.

**Comment by sghai** [comment]
good catch.. lets file all upgrade issue to our new project https://github.com/SatelliteQE/satellite6-upgrade and fix and track them there..

**Comment by sghai** [comment]
closing this issue here as its opened at new place https://github.com/SatelliteQE/satellite6-upgrade/issues/5

**Comment by sghai** [comment]
[10.x.x.x] run: docker exec aa6c011f07b0dd419017c7434dffec328b2fe3afa9354c227f77b4884001e544 subscription-manager refresh
[10.x.x.x] out: Error response from daemon: No such container: aa6c011f07b0dd419017c7434dffec328b2fe3afa9354c227f77b4884001e544
[10.x.x.x] out: 

Fatal error: run() received nonzero return code 1 while executing!
