### ISSUE TITLE
hammer fails with hostname "localhost" does not match the server certificate

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/automation-tools#599]
At Satellite Nightly all hammer operation fails :
```
Could not load the API description from the server: 
hostname "localhost" does not match the server certificate
  - is the server down?
  - was 'foreman-rake apipie:cache' run on the server when using apipie cache? (typical product
```

**Comment by lpramuk** [comment]
On behalf of this issue I filed https://bugzilla.redhat.com/show_bug.cgi?id=1454706 so that I can decorate the code to be executed until the bug is fixed.

**Comment by omaciel** [comment]
Please follow up with an email to mailing list so that the BZ can be fixed asap.
