### ISSUE TITLE
Open up ports for default libvirt setup

### ISSUE THREAD

**Issue by omaciel** [SatelliteQE/automation-tools#639]
If we run the task `setup_default_libvirt` during a Satellite installation, then open up ports for `VNV` as follows:

```firewall-cmd  --service=vnc-server --add-port=5904-5999/tcp --permanent```

Please remember to **restart** the firewall:

```systemctl restart firewalld```

**Comment by pgagne** [comment]
Just wanted to clarify here, we also need to do `firewall-cmd --add-service vnc-server` too.

**Comment by kbidarkar** [comment]
Added in, https://github.com/SatelliteQE/automation-tools/pull/640
