### ISSUE TITLE
rhel-server-rhscl-7-rpms not enabled during capsule install

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/automation-tools#715]
I tried doing a capsule install and noticed that for some reason rhel-server-rhscl-7-rpms wasn't enabled. during the install. 

Its possible that the activation key should of had it enabled. But if thats not the case, we need to enable it before trying to install `satellite-capsule`

**Comment by kbidarkar** [comment]
I think the issue is we need to enable it explicitly as RHSCL and foreman-maintain do not get enabled by default, though the entire product is added to AK. The RHEL and SAT could have automatically got enabled.

**Comment by ntkathole** [comment]
Fixed!
