### ISSUE TITLE
Capsule installer requires wget

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/automation-tools#716]
I ran into an issue using the capsule installer when it was using wget to copy the capsule install script from the satellite to the host. I got a command not found error. 

wget is not usually installed by default. So we either need to install it before hand or use something like curl.

**Comment by kbidarkar** [comment]
Looks like the RHEL7.5 Image that we have already had wget package.
Ok, we can explicitly install wget package.

**Comment by kbidarkar** [comment]
Fixed in #720

**Comment by kbidarkar** [comment]
Also in #721
