### ISSUE TITLE
Capsule installer does not create the right firewall holes

### ISSUE THREAD

**Issue by pgagne** [SatelliteQE/automation-tools#717]
It seems when using the capsule installer, some firewall holes that are created for a satellite are not created for a capsule. 

Here is someones I noticed:

- [ ] libvirt access (tcp+qemu) 
- [ ] vnc ports for VM remote access.

There are potentially more.

**Comment by kbidarkar** [comment]
I feel this is an issue we see now as this get's created as part of setting up libvirt on capsule m for both VNC and Libvirt access )tcp+qemu

This would automatically get configured once, we get past "yum install satellite-capsule" , as it currently fails at this stage.

I am fixing for the RHSCL and foreman-maintain stuff, post which I believe this should not be an issue.

**Comment by san7ket** [comment]
Please feel free to re-open if this still needs fixing
