### ISSUE TITLE
Provide ability to create new repofile after installing 

### ISSUE THREAD

**Issue by cswiii** [SatelliteQE/automation-tools#72]
Let's say we want to test an upgrade after installing a product (say, GA compose).  The cycle might be something like

* Install product
* Run populate test
* Point server to repo with latest compose
* Install new updates and restart

If we get issues #71 resolved, it seems it could work something like

* cdn_install
* (automated population)
* generate_compose_repofile
* update_rpms

This would help catch dependency issues in rpm or the like, as well.

**Comment by elyezer** [comment]
#170 is merged, closing this.
