### ISSUE TITLE
Add ability to assert for downloaded manifest content

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/automation-tools#786]
This is needed to be able to assert that automation manifest contains only subscriptions we want there.

I propose this:
```
--- a/automation_tools/__init__.py
+++ b/automation_tools/__init__.py
@@ -3115,6 +3115,19 @@ def download_manifest(url=None, consumer=None):
                          ' session and distributor hash')
 
 
+def validate_manifest(manifest_file):
+    """Make sure that manifest contains only subscriptions specified in config file
+    specified in environment variable:
+
+    EXP_SUBS_FILE
+        List of subscriptions which are supposed to be in the manifest (one
+        subscription name per line). No other subscription is allowed.
+
+    :param manifest_file: Where is the manifest to investigate.
+    """
+    ### do the check, return True/False
+
+
 def relink_manifest(manifest_file=None):
     """Links the latest downloaded manifest file to the manifest_latest.zip
     softlink.
@@ -3123,6 +3136,8 @@ def relink_manifest(manifest_file=None):
     """
     if manifest_file is None:
         manifest_file = download_manifest()
+        if os.environ.get('EXP_SUBS_FILE', None) is not None:
+            assert validate_manifest(manifest_file)
     if not manifest_file:
         print('manifest_file is not populated.')
         sys.exit(1)
```

Is that right way to do it?

**Comment by jhutar** [comment]
Hello @lpramuk, @san7ket and @ntkathole could you please review if going this direction makes sense?

**Comment by rplevka** [comment]
I wouldn't assert the downloaded manifest (although it would be an ultimate assertion), but i would rather use the Portal api to list the attached subs for the account in a form of json. The manifest downloader already uses the API, all we need to do is to extend the script. I think @vijay8451 was working on it?

**Comment by jhutar** [comment]
Hello @rplevka! Intent here is to catch situation when somebody adds some subscription to the manifest which we do not want to have in it - so this job starts screaming "something is wrong" and wont "propagate" the manifest to the automation.

**Comment by ntkathole** [comment]
@jhutar approach looks good to me!
