### ISSUE TITLE
Fix automation to use foreman-maintain to install packages instead of using yum.

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/automation-tools#800]
As per recent changes in version-locking feature of foreman-maintain, user will only be able to install/update packages using foreman-maintain.
If user wants to install/update packages freely(using yum) then he needs to either disable
packages-locking or add the name of package to whitelist file, but this approach is not supported.

Because of this change we need to make sure that instead of yum we use foreman-maintain to install packages.
Reference:- [https://github.com/theforeman/foreman_maintain/pull/278](https://github.com/theforeman/foreman_maintain/pull/278)

**Comment by lpramuk** [comment]
We can run every yum command with 
```--disable-plugin=versionlock``` and yum works just fine
